sonar.projectKey=nodejs-app
sonar.organization=pramirez-profe

sonar.sources=src
sonar.tests=tests
sonar.exclusions=**/node_modules/**,coverage/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=src/index.js
